name: CI

on:
  push:
    branches: [ ci ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-lastest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v7
      with:
        node-version: 24
    - name: Cypress run
      uses: cypress-io/github-action@v7
      continue-on-error: true
      with:
        install-command: npm install
        browser: chrome
    - name: Publish Report
      uses: peaceiris/actions-gh-pages@v4
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome
